7.0.2-dev.1
rescript-lang/bucklescript.github.io pull request #185
Opened 2019-12-20 07:56 UTC by bobzhang

2019-12-20 09:46 UTC, ryyppy requested changes
I rephrased a lot of stuff and structured the examples in multiple, more comprehensible steps (starting out easy with variants, and go up to GADTs). I tried to add notes on each example, so ppl can follow along on what e.g. the `Any` ADT is about. I also tried to apply some practical context, to answer questions such as "why would I need this as a JS dev?".

I also made sure to explain what `unboxing` means, right after the very formal definition of the OCaml manual. I hope I got everything right?

2019-12-20 09:46 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +This release contains several bug fixes for refmt(the reason parser), we also spend quite some time improving compiler performance, for example, we optimized all our vendored type specialized hash ba
This release contains several bug fixes for refmt (updated from 3.5.1 to 3.5.4). We also spent quite some time improving the compiler performance. For example, we optimized our specialized hash based data structures, which means that we can expect a 5% better build time performance. We would like to collect more benchmark data, so we are happy for any feedback / benchmarks from our community!

2019-12-20 09:46 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +A highlighting feature is that we support a generalized unboxed support:
A highlighting feature is that we added Generalized Unboxed Support (so called `[@unboxed]` annotations). Here's a short definition from the official [OCaml Manual](https://caml.inria.fr/pub/docs/manual-ocaml/manual035.html):

2019-12-20 09:46 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +The great thing is such restriction is only in native backend but does not apply to BuckleScript so it is generally more useful and will not give your confusing error message.
**Note:** The restrictions for GADTs does apply to OCaml's native compilation, but not to BuckleScript's JavaScript compilation, so we will get the maximum value with less confusing error messages!

2019-12-20 09:46 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +The cool thing is that it not only provides your some optimizations but makes something impossible before now possible. A sophiscated explanation is listed in the end (feel free to ignore the paragra
The exciting thing about this feature is that we will now have more ways of expressing our programs in our typical type safe records and variants without sacrificing on runtime performance ("zero interop"). 

The best way to understand this feature is by looking at the following examples:

**Unboxed variants:**

```reason
[@ocaml.unboxed]
type t = A(int);
let x = A(3);
```

will translate to following JS:

```js
var x = 3;
```

As you can see, we are "unboxing" the `int` value from the internal variant representation, so the variant will get completely invisible to the runtime. Great for e.g. mapping to stringly typed JavaScript enums!

**Unboxed Records (1 field only)**

```reason
[@ocaml.unboxed]
type t2 = {f: string};
let x = {f: "foo"};
```

will translate to following JS:

```js
var x = "foo";
```

The same principle as with variants. Now a lot of people will probably ask: "Why would I ever want a 1 field record?". There are multiple reasons, one of them would be a `ref` type, which is just a syntax sugar for a `{ contents: 'a}` record.

Another use case is for expressing high rank polymorphism without cost:

```reason
[@unboxed]
type r = {f: 'a. 'a => 'a};
let map_pair = (r, (p1, p2)) => (r.f(p1), r.f(p2));
```

**Note:** `'a. 'a => 'a` describes a polymorphic function interface, where `'a` can be called with many different types (e.g. `f(1)` and `f("hi")`). The compiler will not try to lock `'a` for the first type it sees (e.g. the `int`) on the first call site. The parameter `'a` is therefore polymorphic!

By `unboxing` those records with one polymorphic function,  we will get rid of [value restriction for our existing encoding of uncurried function](https://github.com/BuckleScript/bucklescript/issues/4058), this will be a major feature!

**Unboxed GADTs:**

Since GADTs are lesser known in Reason syntax, we also added some OCaml snippet to get a better idea of how the example data structure is defined.

```reason
[@unboxed]
type t = 
  | Any ('a) ; 

let array = [|Any(3), Any("a")|];
```
```ocaml
(* OCaml *)
type t = 
  | Any : 'a -> t
[@@unboxed]

let array = [|Any 3; Any "a"|]
```

The examples above will translate to following JS:

```js
var hi = [ 3, 2, "x"];
```

As you can already tell, this feature will give us way better possibilities to do interop with polymorphic array representations in JavaScript (without loosing any type safetiness!).

**Note:** Even if this GADT `t` contains an ADT `Any`, it doesn't mean that it's the same as `any` in TypeScript. An `Any` value is constrained to a certain interface (`'a -> t`), the array `[|Any(3), Any("a")|]` is inferred as a `array(t)`. When users try to use `Any` values, they need to unpack them, process the value inside, and repack them again. Pretty neat, right?

2019-12-20 09:46 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +By making use of this,  we will get rid of [value restriction for our existing encoding of uncurried function](https://github.com/BuckleScript/bucklescript/issues/4058), this will be a major feature!
Scrap line 27 - 70 in favor of the example comment above

2019-12-20 09:46 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +
### Conclusion

This release will introduces the `[@unbox]` annotation to give us better ways to do zero-interop with variants, records, higher kinded polymorphic functions and GADTs. Under the hood improvements will give us better performance as well!

We are really excited about these changes, and we hope so are you. Please check out our newest `bs-platform@7.0.2-dev.1` release and let us know if you find any issues!

A detailed list of changes is available here: https://github.com/BuckleScript/bucklescript/blob/master/Changes.md#702

Happy hacking!

### Appendix

**A sophiscated explanation on why `unboxed` lift some OCaml's type system limitations**

```text
structural types (objects, classes, polymorphic variants, functions, etc) in OCaml are regular types, ocaml always do the expansion when dealing with such types, there is some limitations for such structural types, for example, non regular definitions are not allowed. Non structural types (variants, records) does not have such limitations, with `unboxed`, we can use non structural types as an indirection without changing its runtime representations.
```

2019-12-20 14:30 UTC, jdeisenberg commented on website/blog/2019-12-20-release-7-02.md
> +This release contains several bug fixes for refmt(the reason parser), we also spend quite some time improving compiler performance, for example, we optimized all our vendored type specialized hash ba
...(updated from 3.5.1 to 3.5.4). We also spent quite some time...

2019-12-20 14:35 UTC, jdeisenberg commented on website/blog/2019-12-20-release-7-02.md
> +
This release will introduce the `[@unbox]`...higher kinded polymorphic functions, and GADTs.

A sophisticated explanation of why `unboxed` lifts some of OCaml's type system limitations

2019-12-20 14:36 UTC, jdeisenberg commented on website/blog/2019-12-20-release-7-02.md
> +By making use of this,  we will get rid of [value restriction for our existing encoding of uncurried function](https://github.com/BuckleScript/bucklescript/issues/4058), this will be a major feature!
loosing -> losing

2019-12-20 14:41 UTC, jdeisenberg commented on website/blog/2019-12-20-release-7-02.md
> +The great thing is such restriction is only in native backend but does not apply to BuckleScript so it is generally more useful and will not give your confusing error message.
Can you make the text starting "unboxed can be used" into a blockquote instead of a code literal? Otherwise, it appears as a single line that has to be scrolled horizontally.

2019-12-20 15:56 UTC, tsnobip commented on website/blog/2019-12-20-release-7-02.md
> +By making use of this,  we will get rid of [value restriction for our existing encoding of uncurried function](https://github.com/BuckleScript/bucklescript/issues/4058), this will be a major feature!
the last example about high rank polymorphism is in OCaml then Reason while it's the opposite in the other examples, can be confusing.

2019-12-20 16:01 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +By making use of this,  we will get rid of [value restriction for our existing encoding of uncurried function](https://github.com/BuckleScript/bucklescript/issues/4058), this will be a major feature!
@tsnobip that's corrected in my bigger change comment above which is rewriting the whole example section from line 27 - 70

2019-12-20 16:45 UTC, tsnobip commented on website/blog/2019-12-20-release-7-02.md
> +By making use of this,  we will get rid of [value restriction for our existing encoding of uncurried function](https://github.com/BuckleScript/bucklescript/issues/4058), this will be a major feature!
sorry for the useless review then ^^
Wouldn't you need to annotate the GADT as being `t` in the Reason example?
```reason
[@unboxed]
type t = 
  | Any ('a): t; 
```

2019-12-21 03:01 UTC, bobzhang commented on website/blog/2019-12-20-release-7-02.md
> +By making use of this,  we will get rid of [value restriction for our existing encoding of uncurried function](https://github.com/BuckleScript/bucklescript/issues/4058), this will be a major feature!
adapted, thanks

2019-12-21 08:36 UTC, ryyppy approved these changes
Looking good, I added two more minor changes after I read through it a second time.
The blockquote will probably be important, otherwise the appendix code is unreadable

2019-12-21 08:36 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +structural types (objects, classes, polymorphic variants, functions, etc) in OCaml are regular types, ocaml always do the expansion when dealing with such types, there is some limitations for such st
make this a blockquote (>), otherwise it's one long line

2019-12-21 08:36 UTC, ryyppy commented on website/blog/2019-12-20-release-7-02.md
> +**Note**: The restrictions for GADTs does apply to OCaml's native compilation, but not to BuckleScript's JavaScript compilation, so we will get the maximum value with less confusing error messages!
**Note**: The beforementioned restriction about GADTs only applies to OCaml's native compiler, not to BuckleScript's JavaScript compilation. So we will get the maximum value with less confusing error messages!

2019-12-21 10:12 UTC, merged