draft post on exception encoding
rescript-lang/bucklescript.github.io pull request #209
Opened 2020-05-06 09:34 UTC by bobzhang

2020-05-06 09:37 UTC, chenglou commented
cc @ryyppy

2020-05-06 11:52 UTC, ryyppy requested changes
Made some comments, hope this helps!

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +## Why it is tricky to preserve stack-trace in ReasonML exception
```suggestion
## Why it is tricky to preserve stack-traces in ReasonML exceptions
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +In the native backend, the stacktrace handling mechanism is different from JS. In JS VM, the stacktrace is collected immediately when an Error object is thrown, while in native, such data is not atta
```suggestion
Whenever you are using a Reason / OCaml exception (a so called "native exception"), you are actually using a data structure which is not the same as a JS runtime exception. That means that each exception representation invoke different stacktrace handling mechanisms:

In JS, the stacktrace is collected immediately when an Error object is thrown, while in native Reason / OCaml, such data is not attached to the exception object at all (you can't just access `e.stack` to retrieve the stacktrace). This is because collecting the stacktrace in a native environment highly depends on the runtime support (e.g. if a flag was provided to attach the stacktrace data).
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +So, to preserve a clear stacktrace we need change the encoding of the exception in ReasonML to better fit JS use case, this is part of our on-going work to choose optimal encoding for all ReasonML da
```suggestion
We want to change that and provide ways to get the same stacktrace for native exceptions as you would with JS exceptions. This is all part of our on-going work to plan and implement the optimal encoding for all the different ReasonML data types for the JS runtime (like with our previous changes to the `bool`, `unit` and `records` representation as well).
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +
To give you a better understanding on the technical parts, let's compare the old native exception representation to the new one and see how we can benefit from better stacktraces.

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +In ReasonML, exception is structured data, take the two exception definitions below, for example
```suggestion
In ReasonML, an exception is basically structured data. Let's have a look at the two exception definitions below:
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +`exception A` is encoded as an array of 3 slots, the first slot is a block by itself called identity block, while the second slot is for field x and the third slot for field y.
```suggestion
`exception A` is encoded as an array of 3 slots. The first slot is a block by itself (called an *identity block*), while the second slot is for field x and the third slot for field y.
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +The identity block is an array of 2 slots whose first slot is a string like "B", while the second slot is a unique integer, such array in native also has a magic tag 248 for other purposes.
```suggestion
The identity block is an array of 2 slots. The first slot is a string like "B", while the second slot is a unique integer. 
In more detail, the native array will also have a magic tag 248 attached which is not relevant for our purposes though.
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +Previously we more or less faithfully do the similar encoding in BuckleScript compiler, but it is no longer case,  now it is much simplified, take two exception values below for example
```suggestion
## What's the new exception encoding?

We had to simplify and unify the encoding for the different exception cases to make it possible to compile exceptions into an object instead of an array. Let's take a look at the two exception values below for example:
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +It will be compiled into
```suggestion
The two values will be compiled into
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +exceptions with or without payload share the same encoding.
```suggestion
As you can see, all exceptions (no matter with or without payload) share the same encoding.
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +
Compiling to following JS:

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +Here the compiler attached a stacktrace here, it is much simpler since now we compile exception value into an object instead of an array.
```suggestion
You can see in the compiled output that we can now attach the stacktrace very easily, since every exception is now an object instead of an array. Really cool!
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +Don't rely on the key name of `RE_EXN_ID`, it is an implementation detail which you should not rely on and it is subject to be changed into a symbol in the future.
```suggestion
Please note that it's not allowed to rely on the key name of `RE_EXN_ID`. It's an implementation detail which will probably be changed into a symbol in the future.
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +With such nice encoding, a hidden feature called [extensible variant](https://caml.inria.fr/pub/docs/manual-ocaml/extensiblevariants.html) is much more useful. exception in ReasonML is a special inst
```suggestion
With our nice new exception encoding, a hidden feature called [extensible variant](https://caml.inria.fr/pub/docs/manual-ocaml/extensiblevariants.html) is now way more useful. This  is because a native exception in ReasonML is actually a special instance of an extensible variant. They share the same encoding, so both benefit from the new changes!
```

2020-05-06 11:52 UTC, ryyppy commented on website/blog/2020-05-06-exception-encoding.md
> +In the master branch of our compiler, we made some significant improvement in exception encoding: it gives all ReasonML/OCaml exceptions a clear stack-trace when it is thrown. This is particular impo
```suggestion
We just recently made some significant improvements with our new exception encoding and we find it so exciting that we want to highlight the changes and explain a little bit how exceptions work when compiling to JS.

The new encoding allows us to provide proper, clear stacktrace information whenever a Reason/OCaml exception is thrown. This is particular important when you have some code running in production that needs to collect those stacktrace for diagnostics.
 
Now let's get into the details how we changed things up!
```

2020-05-07 01:30 UTC, bobzhang commented on website/blog/2020-05-06-exception-encoding.md
> +
will make a picture for this

2020-05-07 02:03 UTC, merged